upstream user-service {
    server user-service:3001;
}

upstream mini-app {
    server mini-app:80;
}

server {
    listen 80;
    server_name localhost;

    location /api/ {
        proxy_pass http://user-service;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location / {
        proxy_pass http://mini-app;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location /deals/ws {
        proxy_pass http://user-service;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}